<template>
  <div class="container mx-auto p-4 py-10">
    <h1 class="text-3xl font-bold mb-4">Tabla Periódica de los Elementos</h1>
    <input
      v-model="searchQuery"
      type="text"
      placeholder="Buscar elemento..."
      class="mb-4 p-2 border rounded w-full"
    />
    <div class="flex flex-row gap-5">
      <div class="w-2/12 p-4 border rounded">
        <div v-if="selectedElement">
          <h2 class="text-2xl font-bold mb-2">{{ selectedElement.name }}</h2>
          <p><strong>Símbolo:</strong> {{ selectedElement.symbol }}</p>
          <p><strong>Número Atómico:</strong> {{ selectedElement.number }}</p>
          <p><strong>Masa Atómica:</strong> {{ selectedElement.atomicMass }}</p>
          <p><strong>Categoría:</strong> {{ selectedElement.category }}</p>
          <p><strong>Fase:</strong> {{ selectedElement.phase }}</p>
          <!-- Agrega más detalles aquí si es necesario -->
        </div>
      </div>
      <div class="grid grid-cols-18 gap-2 w-10/12">
        <div
          v-for="element in filteredElements"
          :key="element.symbol"
          class="border p-2 text-center cursor-pointer hover:bg-gray-200"
          @click="selectElement(element)"
        >
          <div class="text-xl font-bold">{{ element.symbol }}</div>
          <div class="text-sm">{{ element.number }}</div>
          <!-- <div class="text-sm">{{ element.name }}</div> -->
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

const elements = [
  {
    symbol: 'H',
    number: 1,
    name: 'Hidrógeno',
    atomicMass: 1.008,
    category: 'No metal',
    phase: 'Gas',
  },
  {
    symbol: 'He',
    number: 2,
    name: 'Helio',
    atomicMass: 4.0026,
    category: 'Gas noble',
    phase: 'Gas',
  },
  {
    symbol: 'Li',
    number: 3,
    name: 'Litio',
    atomicMass: 6.94,
    category: 'Metal alcalino',
    phase: 'Sólido',
  },
  {
    symbol: 'Be',
    number: 4,
    name: 'Berilio',
    atomicMass: 9.0122,
    category: 'Metal alcalinotérreo',
    phase: 'Sólido',
  },
  {
    symbol: 'B',
    number: 5,
    name: 'Boro',
    atomicMass: 10.81,
    category: 'Metaloide',
    phase: 'Sólido',
  },
  {
    symbol: 'C',
    number: 6,
    name: 'Carbono',
    atomicMass: 12.011,
    category: 'No metal',
    phase: 'Sólido',
  },
  {
    symbol: 'N',
    number: 7,
    name: 'Nitrógeno',
    atomicMass: 14.007,
    category: 'No metal',
    phase: 'Gas',
  },
  {
    symbol: 'O',
    number: 8,
    name: 'Oxígeno',
    atomicMass: 15.999,
    category: 'No metal',
    phase: 'Gas',
  },
  { symbol: 'F', number: 9, name: 'Flúor', atomicMass: 18.998, category: 'Halógeno', phase: 'Gas' },
  {
    symbol: 'Ne',
    number: 10,
    name: 'Neón',
    atomicMass: 20.18,
    category: 'Gas noble',
    phase: 'Gas',
  },
  {
    symbol: 'Na',
    number: 11,
    name: 'Sodio',
    atomicMass: 22.99,
    category: 'Metal alcalino',
    phase: 'Sólido',
  },
  {
    symbol: 'Mg',
    number: 12,
    name: 'Magnesio',
    atomicMass: 24.305,
    category: 'Metal alcalinotérreo',
    phase: 'Sólido',
  },
  {
    symbol: 'Al',
    number: 13,
    name: 'Aluminio',
    atomicMass: 26.981,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Si',
    number: 14,
    name: 'Silicio',
    atomicMass: 28.085,
    category: 'Metaloide',
    phase: 'Sólido',
  },
  {
    symbol: 'P',
    number: 15,
    name: 'Fósforo',
    atomicMass: 30.974,
    category: 'No metal',
    phase: 'Sólido',
  },
  {
    symbol: 'S',
    number: 16,
    name: 'Azufre',
    atomicMass: 32.06,
    category: 'No metal',
    phase: 'Sólido',
  },
  {
    symbol: 'Cl',
    number: 17,
    name: 'Cloro',
    atomicMass: 35.45,
    category: 'Halógeno',
    phase: 'Gas',
  },
  {
    symbol: 'Ar',
    number: 18,
    name: 'Argón',
    atomicMass: 39.948,
    category: 'Gas noble',
    phase: 'Gas',
  },
  {
    symbol: 'K',
    number: 19,
    name: 'Potasio',
    atomicMass: 39.098,
    category: 'Metal alcalino',
    phase: 'Sólido',
  },
  {
    symbol: 'Ca',
    number: 20,
    name: 'Calcio',
    atomicMass: 40.078,
    category: 'Metal alcalinotérreo',
    phase: 'Sólido',
  },
  {
    symbol: 'Sc',
    number: 21,
    name: 'Escandio',
    atomicMass: 44.956,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Ti',
    number: 22,
    name: 'Titanio',
    atomicMass: 47.867,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'V',
    number: 23,
    name: 'Vanadio',
    atomicMass: 50.942,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Cr',
    number: 24,
    name: 'Cromo',
    atomicMass: 51.996,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Mn',
    number: 25,
    name: 'Manganeso',
    atomicMass: 54.938,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Fe',
    number: 26,
    name: 'Hierro',
    atomicMass: 55.845,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Co',
    number: 27,
    name: 'Cobalto',
    atomicMass: 58.933,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Ni',
    number: 28,
    name: 'Níquel',
    atomicMass: 58.693,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Cu',
    number: 29,
    name: 'Cobre',
    atomicMass: 63.546,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Zn',
    number: 30,
    name: 'Zinc',
    atomicMass: 65.38,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Ga',
    number: 31,
    name: 'Galio',
    atomicMass: 69.723,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Ge',
    number: 32,
    name: 'Germanio',
    atomicMass: 72.63,
    category: 'Metaloide',
    phase: 'Sólido',
  },
  {
    symbol: 'As',
    number: 33,
    name: 'Arsénico',
    atomicMass: 74.922,
    category: 'Metaloide',
    phase: 'Sólido',
  },
  {
    symbol: 'Se',
    number: 34,
    name: 'Selenio',
    atomicMass: 78.971,
    category: 'No metal',
    phase: 'Sólido',
  },
  {
    symbol: 'Br',
    number: 35,
    name: 'Bromo',
    atomicMass: 79.904,
    category: 'Halógeno',
    phase: 'Líquido',
  },
  {
    symbol: 'Kr',
    number: 36,
    name: 'Kriptón',
    atomicMass: 83.798,
    category: 'Gas noble',
    phase: 'Gas',
  },
  {
    symbol: 'Rb',
    number: 37,
    name: 'Rubidio',
    atomicMass: 85.468,
    category: 'Metal alcalino',
    phase: 'Sólido',
  },
  {
    symbol: 'Sr',
    number: 38,
    name: 'Estroncio',
    atomicMass: 87.62,
    category: 'Metal alcalinotérreo',
    phase: 'Sólido',
  },
  {
    symbol: 'Y',
    number: 39,
    name: 'Itrio',
    atomicMass: 88.906,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Zr',
    number: 40,
    name: 'Circonio',
    atomicMass: 91.224,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Nb',
    number: 41,
    name: 'Niobio',
    atomicMass: 92.906,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Mo',
    number: 42,
    name: 'Molibdeno',
    atomicMass: 95.95,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Tc',
    number: 43,
    name: 'Tecnecio',
    atomicMass: 98,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Ru',
    number: 44,
    name: 'Rutenio',
    atomicMass: 101.07,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Rh',
    number: 45,
    name: 'Rodio',
    atomicMass: 102.91,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Pd',
    number: 46,
    name: 'Paladio',
    atomicMass: 106.42,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Ag',
    number: 47,
    name: 'Plata',
    atomicMass: 107.87,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Cd',
    number: 48,
    name: 'Cadmio',
    atomicMass: 112.41,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'In',
    number: 49,
    name: 'Indio',
    atomicMass: 114.82,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Sn',
    number: 50,
    name: 'Estaño',
    atomicMass: 118.71,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Sb',
    number: 51,
    name: 'Antimonio',
    atomicMass: 121.76,
    category: 'Metaloide',
    phase: 'Sólido',
  },
  {
    symbol: 'Te',
    number: 52,
    name: 'Telurio',
    atomicMass: 127.6,
    category: 'Metaloide',
    phase: 'Sólido',
  },
  {
    symbol: 'I',
    number: 53,
    name: 'Yodo',
    atomicMass: 126.9,
    category: 'Halógeno',
    phase: 'Sólido',
  },
  {
    symbol: 'Xe',
    number: 54,
    name: 'Xenón',
    atomicMass: 131.29,
    category: 'Gas noble',
    phase: 'Gas',
  },
  {
    symbol: 'Cs',
    number: 55,
    name: 'Cesio',
    atomicMass: 132.91,
    category: 'Metal alcalino',
    phase: 'Sólido',
  },
  {
    symbol: 'Ba',
    number: 56,
    name: 'Bario',
    atomicMass: 137.33,
    category: 'Metal alcalinotérreo',
    phase: 'Sólido',
  },
  {
    symbol: 'La',
    number: 57,
    name: 'Lantano',
    atomicMass: 138.91,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  // Add more elements here if needed
  {
    symbol: 'Ce',
    number: 58,
    name: 'Cerio',
    atomicMass: 140.12,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Pr',
    number: 59,
    name: 'Praseodimio',
    atomicMass: 140.91,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Nd',
    number: 60,
    name: 'Neodimio',
    atomicMass: 144.24,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Pm',
    number: 61,
    name: 'Prometio',
    atomicMass: 145,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Sm',
    number: 62,
    name: 'Samario',
    atomicMass: 150.36,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Eu',
    number: 63,
    name: 'Europio',
    atomicMass: 151.96,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Gd',
    number: 64,
    name: 'Gadolinio',
    atomicMass: 157.25,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Tb',
    number: 65,
    name: 'Terbio',
    atomicMass: 158.93,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Dy',
    number: 66,
    name: 'Disprosio',
    atomicMass: 162.5,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Ho',
    number: 67,
    name: 'Holmio',
    atomicMass: 164.93,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Er',
    number: 68,
    name: 'Erbio',
    atomicMass: 167.26,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Tm',
    number: 69,
    name: 'Tulio',
    atomicMass: 168.93,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Yb',
    number: 70,
    name: 'Iterbio',
    atomicMass: 173.04,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Lu',
    number: 71,
    name: 'Lutecio',
    atomicMass: 174.97,
    category: 'Lantánido',
    phase: 'Sólido',
  },
  {
    symbol: 'Hf',
    number: 72,
    name: 'Hafnio',
    atomicMass: 178.49,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Ta',
    number: 73,
    name: 'Tantalio',
    atomicMass: 180.95,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'W',
    number: 74,
    name: 'Wolframio',
    atomicMass: 183.84,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Re',
    number: 75,
    name: 'Renio',
    atomicMass: 186.21,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Os',
    number: 76,
    name: 'Osmio',
    atomicMass: 190.23,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Ir',
    number: 77,
    name: 'Iridio',
    atomicMass: 192.22,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Pt',
    number: 78,
    name: 'Platino',
    atomicMass: 195.08,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Au',
    number: 79,
    name: 'Oro',
    atomicMass: 196.97,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Hg',
    number: 80,
    name: 'Mercurio',
    atomicMass: 200.59,
    category: 'Metal de transición',
    phase: 'Líquido',
  },
  {
    symbol: 'Tl',
    number: 81,
    name: 'Talio',
    atomicMass: 204.38,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Pb',
    number: 82,
    name: 'Plomo',
    atomicMass: 207.2,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Bi',
    number: 83,
    name: 'Bismuto',
    atomicMass: 208.98,
    category: 'Metal de transición',
    phase: 'Sólido',
  },
  {
    symbol: 'Po',
    number: 84,
    name: 'Polonio',
    atomicMass: 209,
    category: 'Metaloide',
    phase: 'Sólido',
  },
  {
    symbol: 'At',
    number: 85,
    name: 'Astato',
    atomicMass: 210,
    category: 'Halógeno',
    phase: 'Sólido',
  },
  {
    symbol: 'Rn',
    number: 86,
    name: 'Radón',
    atomicMass: 222,
    category: 'Gas noble',
    phase: 'Gas',
  },
  {
    symbol: 'Fr',
    number: 87,
    name: 'Francio',
    atomicMass: 223,
    category: 'Metal alcalino',
    phase: 'Sólido',
  },
  {
    symbol: 'Ra',
    number: 88,
    name: 'Radio',
    atomicMass: 226,
    category: 'Metal alcalinotérreo',
    phase: 'Sólido',
  },
  {
    symbol: 'Ac',
    number: 89,
    name: 'Actinio',
    atomicMass: 227,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Th',
    number: 90,
    name: 'Torio',
    atomicMass: 232.04,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Pa',
    number: 91,
    name: 'Protactinio',
    atomicMass: 231.04,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'U',
    number: 92,
    name: 'Uranio',
    atomicMass: 238.03,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Np',
    number: 93,
    name: 'Neptunio',
    atomicMass: 237,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Pu',
    number: 94,
    name: 'Plutonio',
    atomicMass: 244,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Am',
    number: 95,
    name: 'Americio',
    atomicMass: 243,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Cm',
    number: 96,
    name: 'Curio',
    atomicMass: 247,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Bk',
    number: 97,
    name: 'Berkelio',
    atomicMass: 247,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Cf',
    number: 98,
    name: 'Californio',
    atomicMass: 251,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Es',
    number: 99,
    name: 'Einstenio',
    atomicMass: 252,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Fm',
    number: 100,
    name: 'Fermio',
    atomicMass: 257,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Md',
    number: 101,
    name: 'Mendelevio',
    atomicMass: 258,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'No',
    number: 102,
    name: 'Nobelio',
    atomicMass: 259,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Lr',
    number: 103,
    name: 'Lawrencio',
    atomicMass: 262,
    category: 'Actínido',
    phase: 'Sólido',
  },
  {
    symbol: 'Rf',
    number: 104,
    name: 'Rutherfordio',
    atomicMass: 267,
    category: 'Metal de transición',
    phase: 'Desconocido',
  },
  {
    symbol: 'Db',
    number: 105,
    name: 'Dubnio',
    atomicMass: 270,
    category: 'Metal de transición',
    phase: 'Desconocido',
  },
  {
    symbol: 'Sg',
    number: 106,
    name: 'Seaborgio',
    atomicMass: 271,
    category: 'Metal de transición',
    phase: 'Desconocido',
  },
  {
    symbol: 'Bh',
    number: 107,
    name: 'Bohrio',
    atomicMass: 270,
    category: 'Metal de transición',
    phase: 'Desconocido',
  },
  {
    symbol: 'Hs',
    number: 108,
    name: 'Hassio',
    atomicMass: 277,
    category: 'Metal de transición',
    phase: 'Desconocido',
  },
  {
    symbol: 'Mt',
    number: 109,
    name: 'Meitnerio',
    atomicMass: 278,
    category: 'Metal de transición',
    phase: 'Desconocido',
  },
  {
    symbol: 'Ds',
    number: 110,
    name: 'Darmstadtio',
    atomicMass: 281,
    category: 'Metal de transición',
    phase: 'Desconocido',
  },
  {
    symbol: 'Rg',
    number: 111,
    name: 'Roentgenio',
    atomicMass: 282,
    category: 'Metal de transición',
    phase: 'Desconocido',
  },
  {
    symbol: 'Cn',
    number: 112,
    name: 'Copernicio',
    atomicMass: 285,
    category: 'Metal de transición',
    phase: 'Desconocido',
  },
  {
    symbol: 'Nh',
    number: 113,
    name: 'Nihonio',
    atomicMass: 286,
    category: 'Desconocido',
    phase: 'Desconocido',
  },
  {
    symbol: 'Fl',
    number: 114,
    name: 'Flerovio',
    atomicMass: 289,
    category: 'Desconocido',
    phase: 'Desconocido',
  },
  {
    symbol: 'Mc',
    number: 115,
    name: 'Moscovio',
    atomicMass: 290,
    category: 'Desconocido',
    phase: 'Desconocido',
  },
  {
    symbol: 'Lv',
    number: 116,
    name: 'Livermorio',
    atomicMass: 293,
    category: 'Desconocido',
    phase: 'Desconocido',
  },
  {
    symbol: 'Ts',
    number: 117,
    name: 'Tenesino',
    atomicMass: 294,
    category: 'Desconocido',
    phase: 'Desconocido',
  },
  {
    symbol: 'Og',
    number: 118,
    name: 'Oganesón',
    atomicMass: 294,
    category: 'Desconocido',
    phase: 'Desconocido',
  },
]

const searchQuery = ref('')
interface Element {
  symbol: string
  number: number
  name: string
  atomicMass: number
  category: string
  phase: string
}

const selectedElement = ref<Element | null>(null)

const filteredElements = computed(() => {
  return elements.filter(
    (element) =>
      element.name.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      element.symbol.toLowerCase().includes(searchQuery.value.toLowerCase()),
  )
})

const selectElement = (element: Element) => {
  selectedElement.value = element
}
</script>

<style scoped>
.container {
  max-width: 1200px;
}
.grid {
  display: grid;
  grid-template-columns: repeat(18, minmax(0, 1fr));
}
</style>
